# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BMI',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='female', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
