# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160316_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='BMI',
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=123, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[(0, 'female'), (1, 'male')], max_length=1),
        ),
    ]
