# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160316_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BMI',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=1),
        ),
    ]
